package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ApplForms generated by hbm2java
 */
@SuppressWarnings("serial")
public class ApplForms implements java.io.Serializable {

	private Integer id;
	private Forms forms;
	private Integer applId;
	private String controlFullGrantNum;
	private Integer updateStamp;
	private Integer agtId;

	public ApplForms() {
	}

	public ApplForms(Integer id, Forms forms) {
		this.id = id;
		this.forms = forms;
	}

	public ApplForms(Integer id, Forms forms, Integer applId, String controlFullGrantNum, Integer updateStamp, Integer agtId) {
		this.id = id;
		this.forms = forms;
		this.applId = applId;
		this.controlFullGrantNum = controlFullGrantNum;
		this.updateStamp = updateStamp;
		this.agtId = agtId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Forms getForms() {
		return this.forms;
	}

	public void setForms(Forms forms) {
		this.forms = forms;
	}

	public Integer getApplId() {
		return this.applId;
	}

	public void setApplId(Integer applId) {
		this.applId = applId;
	}

	public String getControlFullGrantNum() {
		return this.controlFullGrantNum;
	}

	public void setControlFullGrantNum(String controlFullGrantNum) {
		this.controlFullGrantNum = controlFullGrantNum;
	}

	public Integer getUpdateStamp() {
		return this.updateStamp;
	}

	public void setUpdateStamp(Integer updateStamp) {
		this.updateStamp = updateStamp;
	}

	public Integer getAgtId() {
		return this.agtId;
	}

	public void setAgtId(Integer agtId) {
		this.agtId = agtId;
	}

}
