package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * FormTemplates generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormTemplates implements java.io.Serializable {

	private Integer id;
	private FormModules formModules;
	private String templateHtml;
	private Integer revisionNum;
	private Date createDate;
	private Integer updateStamp;
	private String templateXml;
	private String description;
	private Date gsfbChangeDate;
	private String gsfbChangedUserId;
	private String gsfbCreatedUserId;
	private String name;
	private String templateUuid;
	private List<FormElements> formElements = new ArrayList<FormElements>();
	// No need for hashCode() and equal() methods. This is inside a session and Hibernate guarantees equivalence of persistent identity (database row) and Java identity inside a particular session scope.
	private Set<Forms> forms = new HashSet<Forms>(0);
	private Set<FormGrantMatrix> formGrantMatrixes = new HashSet<FormGrantMatrix>(0);
	private Set<FormTemplatesMatrix> formTemplatesMatrixes = new HashSet<FormTemplatesMatrix>(0);

	public FormTemplates() {
	}

	public FormTemplates(Integer id, String templateHtml, Integer revisionNum, Date createDate) {
		this.id = id;
		this.templateHtml = templateHtml;
		this.revisionNum = revisionNum;
		this.createDate = createDate;
	}

	public FormTemplates(Integer id, FormModules formModules, String templateHtml, Integer revisionNum, Integer updateStamp,
			String templateXml, String description, Date gsfbChangeDate, String gsfbChangedUserId,
			String gsfbCreatedUserId, String name, String templateUuid, Set<Forms> forms, Set<FormGrantMatrix> formGrantMatrixes,
			List<FormElements> formElements, Set<FormTemplatesMatrix> formTemplatesMatrixes, Date createDate) {
		this.id = id;
		this.formModules = formModules;
		this.templateHtml = templateHtml;
		this.revisionNum = revisionNum;
		this.updateStamp = updateStamp;
		this.templateXml = templateXml;
		this.description = description;
		this.gsfbChangeDate = gsfbChangeDate;
		this.gsfbChangedUserId = gsfbChangedUserId;
		this.gsfbCreatedUserId = gsfbCreatedUserId;
		this.name = name;
		this.templateUuid = templateUuid;
		this.forms = forms;
		this.formGrantMatrixes = formGrantMatrixes;
		this.formElements = formElements;
		this.formTemplatesMatrixes = formTemplatesMatrixes;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormModules getFormModules() {
		return this.formModules;
	}

	public void setFormModules(FormModules formModules) {
		this.formModules = formModules;
	}

	public String getTemplateHtml() {
		return this.templateHtml;
	}

	public void setTemplateHtml(String templateHtml) {
		this.templateHtml = templateHtml;
	}

	public Integer getRevisionNum() {
		return this.revisionNum;
	}

	public void setRevisionNum(Integer revisionNum) {
		this.revisionNum = revisionNum;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getUpdateStamp() {
		return this.updateStamp;
	}

	public void setUpdateStamp(Integer updateStamp) {
		this.updateStamp = updateStamp;
	}

	public String getTemplateXml() {
		return this.templateXml;
	}

	public void setTemplateXml(String templateXml) {
		this.templateXml = templateXml;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getGsfbChangeDate() {
		return this.gsfbChangeDate;
	}

	public void setGsfbChangeDate(Date gsfbChangeDate) {
		this.gsfbChangeDate = gsfbChangeDate;
	}

	public String getGsfbChangedUserId() {
		return this.gsfbChangedUserId;
	}

	public void setGsfbChangedUserId(String gsfbChangedUserId) {
		this.gsfbChangedUserId = gsfbChangedUserId;
	}

	public String getGsfbCreatedUserId() {
		return this.gsfbCreatedUserId;
	}

	public void setGsfbCreatedUserId(String gsfbCreatedUserId) {
		this.gsfbCreatedUserId = gsfbCreatedUserId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTemplateUuid() {
		return this.templateUuid;
	}

	public void setTemplateUuid(String templateUuid) {
		this.templateUuid = templateUuid;
	}

	public Set<Forms> getForms() {
		return this.forms;
	}

	public void setForms(Set<Forms> forms) {
		this.forms = forms;
	}

	public Set<FormGrantMatrix> getFormGrantMatrixes() {
		return this.formGrantMatrixes;
	}

	public void setFormGrantMatrixes(Set<FormGrantMatrix> formGrantMatrixes) {
		this.formGrantMatrixes = formGrantMatrixes;
	}

	public List<FormElements> getFormElements() {
		return this.formElements;
	}

	public void setFormElements(List<FormElements> formElements) {
		this.formElements = formElements;
	}

	public Set<FormTemplatesMatrix> getFormTemplatesMatrixes() {
		return this.formTemplatesMatrixes;
	}

	public void setFormTemplatesMatrixes(Set<FormTemplatesMatrix> formTemplatesMatrixes) {
		this.formTemplatesMatrixes = formTemplatesMatrixes;
	}

}
