package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormInactiveTypeMech generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormInactiveTypeMech implements java.io.Serializable {

	private FormInactiveTypeMechId id;

	public FormInactiveTypeMech() {
	}

	public FormInactiveTypeMech(FormInactiveTypeMechId id) {
		this.id = id;
	}

	public FormInactiveTypeMechId getId() {
		return this.id;
	}

	public void setId(FormInactiveTypeMechId id) {
		this.id = id;
	}

}
