package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormInactiveTypeMechId generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormInactiveTypeMechId implements java.io.Serializable {

	private String module;
	private String applTypeCode;
	private String activityCode;

	public FormInactiveTypeMechId() {
	}

	public FormInactiveTypeMechId(String module, String applTypeCode, String activityCode) {
		this.module = module;
		this.applTypeCode = applTypeCode;
		this.activityCode = activityCode;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getApplTypeCode() {
		return this.applTypeCode;
	}

	public void setApplTypeCode(String applTypeCode) {
		this.applTypeCode = applTypeCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormInactiveTypeMechId))
			return false;
		FormInactiveTypeMechId castOther = (FormInactiveTypeMechId) other;

		return ((this.getModule() == castOther.getModule()) || (this.getModule() != null
				&& castOther.getModule() != null && this.getModule().equals(castOther.getModule())))
				&& ((this.getApplTypeCode() == castOther.getApplTypeCode())
						|| (this.getApplTypeCode() != null && castOther.getApplTypeCode() != null
								&& this.getApplTypeCode().equals(castOther.getApplTypeCode())))
				&& ((this.getActivityCode() == castOther.getActivityCode())
						|| (this.getActivityCode() != null && castOther.getActivityCode() != null
								&& this.getActivityCode().equals(castOther.getActivityCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getModule() == null ? 0 : this.getModule().hashCode());
		result = 37 * result + (getApplTypeCode() == null ? 0 : this.getApplTypeCode().hashCode());
		result = 37 * result + (getActivityCode() == null ? 0 : this.getActivityCode().hashCode());
		return result;
	}

}
