package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormTemplatesMatrixDraft generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormTemplatesMatrixDraft implements java.io.Serializable {

	private Integer id;
	private FormTemplatesDraft formTemplatesDraft;
	private String formRoleCode;
	private String applTypeCode;
	private String activityCode;

	public FormTemplatesMatrixDraft() {
	}

	public FormTemplatesMatrixDraft(Integer id) {
		this.id = id;
	}

	public FormTemplatesMatrixDraft(Integer id, FormTemplatesDraft formTemplatesDraft, String formRoleCode, String applTypeCode, String activityCode) {
		this.id = id;
		this.formTemplatesDraft = formTemplatesDraft;
		this.formRoleCode = formRoleCode;
		this.applTypeCode = applTypeCode;
		this.activityCode = activityCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormTemplatesDraft getFormTemplatesDraft() {
		return this.formTemplatesDraft;
	}

	public void setFormTemplatesDraft(FormTemplatesDraft formTemplatesDraft) {
		this.formTemplatesDraft = formTemplatesDraft;
	}

	public String getFormRoleCode() {
		return this.formRoleCode;
	}

	public void setFormRoleCode(String formRoleCode) {
		this.formRoleCode = formRoleCode;
	}

	public String getApplTypeCode() {
		return this.applTypeCode;
	}

	public void setApplTypeCode(String applTypeCode) {
		this.applTypeCode = applTypeCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public FormTemplatesMatrix toFormTemplatesMatrix() {
		FormTemplatesMatrix ftm = new FormTemplatesMatrix();
		ftm.setFormRoleCode(this.formRoleCode);
		ftm.setApplTypeCode(this.applTypeCode);
		ftm.setActivityCode(this.activityCode);

		return ftm;
	}
}
