package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FormTemplatesMatrix generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormTemplatesMatrix implements java.io.Serializable {

	private Integer id;
	private FormTemplates formTemplates;
	private String formRoleCode;
	private String applTypeCode;
	private String activityCode;
	private Date startDate;
	private Date endDate;
	private Integer updateStamp;
	// No need for hashCode() and equal() methods. This is inside a session and Hibernate guarantees equivalence of persistent identity (database row) and Java identity inside a particular session scope.
	private Set<Forms> forms = new HashSet<Forms>(0);

	public FormTemplatesMatrix() {
	}

	public FormTemplatesMatrix(Integer id, FormTemplates formTemplates) {
		this.id = id;
		this.formTemplates = formTemplates;
	}

	public FormTemplatesMatrix(Integer id, FormTemplates formTemplates, String formRoleCode, String applTypeCode,
			String activityCode, Date startDate, Date endDate, Integer updateStamp, Set<Forms> forms) {
		this.id = id;
		this.formTemplates = formTemplates;
		this.formRoleCode = formRoleCode;
		this.applTypeCode = applTypeCode;
		this.activityCode = activityCode;
		this.startDate = startDate;
		this.endDate = endDate;
		this.updateStamp = updateStamp;
		this.forms = forms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormTemplates getFormTemplates() {
		return this.formTemplates;
	}

	public void setFormTemplates(FormTemplates formTemplates) {
		this.formTemplates = formTemplates;
	}

	public String getFormRoleCode() {
		return this.formRoleCode;
	}

	public void setFormRoleCode(String formRoleCode) {
		this.formRoleCode = formRoleCode;
	}

	public String getApplTypeCode() {
		return this.applTypeCode;
	}

	public void setApplTypeCode(String applTypeCode) {
		this.applTypeCode = applTypeCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getUpdateStamp() {
		return this.updateStamp;
	}

	public void setUpdateStamp(Integer updateStamp) {
		this.updateStamp = updateStamp;
	}

	public Set<Forms> getForms() {
		return this.forms;
	}

	public void setForms(Set<Forms> forms) {
		this.forms = forms;
	}
}
