package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * FormGrantId generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormGrantId implements java.io.Serializable {

	private Boolean dummyFlag;
	private Boolean onControlFlag;
	private Boolean electronicSubmissionFlag;
	private Integer applId;
	private String fullGrantNum;
	private String rfaPaNumber;
	private String councilMeetingDate;
	private String firstName;
	private String miName;
	private String lastName;
	private String piName;
	private Integer irgPercentileNum;
	private Integer priorityScoreNum;
	private String applTypeCode;
	private String adminPhsOrgCode;
	private String activityCode;
	private Integer serialNum;
	private Integer supportYear;
	private String suffixCode;
	private String applStatusCode;
	private String applStatusGroupCode;
	private String formerNum;
	private Date budgetStartDate;
	private Date latestBudgetStartDate;
	private Integer fy;
	private Integer ipf;
	private String orgName;
	private String withinPaylineFlag;
	private String cayCode;
	private String roleUsageCode;
	private Integer pdNpeId;
	private Integer pdNpnId;
	private String pdLastName;
	private String pdFirstName;
	private String pdMiName;
	private String pdUserId;
	private String gmsCode;
	private Integer gmsNpeId;
	private Integer gmsNpnId;
	private String gmsLastName;
	private String gmsFirstName;
	private String gmsMiName;
	private String gmsUserId;
	private String bkupGmsCode;
	private Integer bkupGmsNpeId;
	private Integer bkupGmsNpnId;
	private String bkupGmsLastName;
	private String bkupGmsFirstName;
	private String bkupGmsMiName;
	private String bkupGmsUserId;
	private String allGmsUserids;
	private String pgmFormStatus;
	private Date pgmFormSubmittedDate;
	private String specFormStatus;
	private Date specFormSubmittedDate;
	private String dmFormStatus;
	private Boolean mbMinorityFlag;
	private String pgmGsReadyFlag;
	private String gpmatsDayCountNum;

	public FormGrantId() {
	}

	public FormGrantId(Boolean dummyFlag, Boolean onControlFlag, Boolean electronicSubmissionFlag, Integer applId,
			String fullGrantNum, String rfaPaNumber, String councilMeetingDate, String firstName, String miName,
			String lastName, String piName, Integer irgPercentileNum, Integer priorityScoreNum, String applTypeCode,
			String adminPhsOrgCode, String activityCode, Integer serialNum, Integer supportYear, String suffixCode,
			String applStatusCode, String applStatusGroupCode, String formerNum, Date budgetStartDate,
			Date latestBudgetStartDate, Integer fy, Integer ipf, String orgName, String withinPaylineFlag,
			String cayCode, String roleUsageCode, Integer pdNpeId, Integer pdNpnId, String pdLastName,
			String pdFirstName, String pdMiName, String pdUserId, String gmsCode, Integer gmsNpeId, Integer gmsNpnId,
			String gmsLastName, String gmsFirstName, String gmsMiName, String gmsUserId, String bkupGmsCode,
			Integer bkupGmsNpeId, Integer bkupGmsNpnId, String bkupGmsLastName, String bkupGmsFirstName,
			String bkupGmsMiName, String bkupGmsUserId, String allGmsUserids, String pgmFormStatus,
			Date pgmFormSubmittedDate, String specFormStatus, Date specFormSubmittedDate, String dmFormStatus,
			Boolean mbMinorityFlag, String pgmGsReadyFlag, String gpmatsDayCountNum) {
		this.dummyFlag = dummyFlag;
		this.onControlFlag = onControlFlag;
		this.electronicSubmissionFlag = electronicSubmissionFlag;
		this.applId = applId;
		this.fullGrantNum = fullGrantNum;
		this.rfaPaNumber = rfaPaNumber;
		this.councilMeetingDate = councilMeetingDate;
		this.firstName = firstName;
		this.miName = miName;
		this.lastName = lastName;
		this.piName = piName;
		this.irgPercentileNum = irgPercentileNum;
		this.priorityScoreNum = priorityScoreNum;
		this.applTypeCode = applTypeCode;
		this.adminPhsOrgCode = adminPhsOrgCode;
		this.activityCode = activityCode;
		this.serialNum = serialNum;
		this.supportYear = supportYear;
		this.suffixCode = suffixCode;
		this.applStatusCode = applStatusCode;
		this.applStatusGroupCode = applStatusGroupCode;
		this.formerNum = formerNum;
		this.budgetStartDate = budgetStartDate;
		this.latestBudgetStartDate = latestBudgetStartDate;
		this.fy = fy;
		this.ipf = ipf;
		this.orgName = orgName;
		this.withinPaylineFlag = withinPaylineFlag;
		this.cayCode = cayCode;
		this.roleUsageCode = roleUsageCode;
		this.pdNpeId = pdNpeId;
		this.pdNpnId = pdNpnId;
		this.pdLastName = pdLastName;
		this.pdFirstName = pdFirstName;
		this.pdMiName = pdMiName;
		this.pdUserId = pdUserId;
		this.gmsCode = gmsCode;
		this.gmsNpeId = gmsNpeId;
		this.gmsNpnId = gmsNpnId;
		this.gmsLastName = gmsLastName;
		this.gmsFirstName = gmsFirstName;
		this.gmsMiName = gmsMiName;
		this.gmsUserId = gmsUserId;
		this.bkupGmsCode = bkupGmsCode;
		this.bkupGmsNpeId = bkupGmsNpeId;
		this.bkupGmsNpnId = bkupGmsNpnId;
		this.bkupGmsLastName = bkupGmsLastName;
		this.bkupGmsFirstName = bkupGmsFirstName;
		this.bkupGmsMiName = bkupGmsMiName;
		this.bkupGmsUserId = bkupGmsUserId;
		this.allGmsUserids = allGmsUserids;
		this.pgmFormStatus = pgmFormStatus;
		this.pgmFormSubmittedDate = pgmFormSubmittedDate;
		this.specFormStatus = specFormStatus;
		this.specFormSubmittedDate = specFormSubmittedDate;
		this.dmFormStatus = dmFormStatus;
		this.mbMinorityFlag = mbMinorityFlag;
		this.pgmGsReadyFlag = pgmGsReadyFlag;
		this.gpmatsDayCountNum = gpmatsDayCountNum;
	}

	public Boolean getDummyFlag() {
		return this.dummyFlag;
	}

	public void setDummyFlag(Boolean dummyFlag) {
		this.dummyFlag = dummyFlag;
	}

	public Boolean getOnControlFlag() {
		return this.onControlFlag;
	}

	public void setOnControlFlag(Boolean onControlFlag) {
		this.onControlFlag = onControlFlag;
	}

	public Boolean getElectronicSubmissionFlag() {
		return this.electronicSubmissionFlag;
	}

	public void setElectronicSubmissionFlag(Boolean electronicSubmissionFlag) {
		this.electronicSubmissionFlag = electronicSubmissionFlag;
	}

	public Integer getApplId() {
		return this.applId;
	}

	public void setApplId(Integer applId) {
		this.applId = applId;
	}

	public String getFullGrantNum() {
		return this.fullGrantNum;
	}

	public void setFullGrantNum(String fullGrantNum) {
		this.fullGrantNum = fullGrantNum;
	}

	public String getRfaPaNumber() {
		return this.rfaPaNumber;
	}

	public void setRfaPaNumber(String rfaPaNumber) {
		this.rfaPaNumber = rfaPaNumber;
	}

	public String getCouncilMeetingDate() {
		return this.councilMeetingDate;
	}

	public void setCouncilMeetingDate(String councilMeetingDate) {
		this.councilMeetingDate = councilMeetingDate;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiName() {
		return this.miName;
	}

	public void setMiName(String miName) {
		this.miName = miName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPiName() {
		return this.piName;
	}

	public void setPiName(String piName) {
		this.piName = piName;
	}

	public Integer getIrgPercentileNum() {
		return this.irgPercentileNum;
	}

	public void setIrgPercentileNum(Integer irgPercentileNum) {
		this.irgPercentileNum = irgPercentileNum;
	}

	public Integer getPriorityScoreNum() {
		return this.priorityScoreNum;
	}

	public void setPriorityScoreNum(Integer priorityScoreNum) {
		this.priorityScoreNum = priorityScoreNum;
	}

	public String getApplTypeCode() {
		return this.applTypeCode;
	}

	public void setApplTypeCode(String applTypeCode) {
		this.applTypeCode = applTypeCode;
	}

	public String getAdminPhsOrgCode() {
		return this.adminPhsOrgCode;
	}

	public void setAdminPhsOrgCode(String adminPhsOrgCode) {
		this.adminPhsOrgCode = adminPhsOrgCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public Integer getSerialNum() {
		return this.serialNum;
	}

	public void setSerialNum(Integer serialNum) {
		this.serialNum = serialNum;
	}

	public Integer getSupportYear() {
		return this.supportYear;
	}

	public void setSupportYear(Integer supportYear) {
		this.supportYear = supportYear;
	}

	public String getSuffixCode() {
		return this.suffixCode;
	}

	public void setSuffixCode(String suffixCode) {
		this.suffixCode = suffixCode;
	}

	public String getApplStatusCode() {
		return this.applStatusCode;
	}

	public void setApplStatusCode(String applStatusCode) {
		this.applStatusCode = applStatusCode;
	}

	public String getApplStatusGroupCode() {
		return this.applStatusGroupCode;
	}

	public void setApplStatusGroupCode(String applStatusGroupCode) {
		this.applStatusGroupCode = applStatusGroupCode;
	}

	public String getFormerNum() {
		return this.formerNum;
	}

	public void setFormerNum(String formerNum) {
		this.formerNum = formerNum;
	}

	public Date getBudgetStartDate() {
		return this.budgetStartDate;
	}

	public void setBudgetStartDate(Date budgetStartDate) {
		this.budgetStartDate = budgetStartDate;
	}

	public Date getLatestBudgetStartDate() {
		return this.latestBudgetStartDate;
	}

	public void setLatestBudgetStartDate(Date latestBudgetStartDate) {
		this.latestBudgetStartDate = latestBudgetStartDate;
	}

	public Integer getFy() {
		return this.fy;
	}

	public void setFy(Integer fy) {
		this.fy = fy;
	}

	public Integer getIpf() {
		return this.ipf;
	}

	public void setIpf(Integer ipf) {
		this.ipf = ipf;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getWithinPaylineFlag() {
		return this.withinPaylineFlag;
	}

	public void setWithinPaylineFlag(String withinPaylineFlag) {
		this.withinPaylineFlag = withinPaylineFlag;
	}

	public String getCayCode() {
		return this.cayCode;
	}

	public void setCayCode(String cayCode) {
		this.cayCode = cayCode;
	}

	public String getRoleUsageCode() {
		return this.roleUsageCode;
	}

	public void setRoleUsageCode(String roleUsageCode) {
		this.roleUsageCode = roleUsageCode;
	}

	public Integer getPdNpeId() {
		return this.pdNpeId;
	}

	public void setPdNpeId(Integer pdNpeId) {
		this.pdNpeId = pdNpeId;
	}

	public Integer getPdNpnId() {
		return this.pdNpnId;
	}

	public void setPdNpnId(Integer pdNpnId) {
		this.pdNpnId = pdNpnId;
	}

	public String getPdLastName() {
		return this.pdLastName;
	}

	public void setPdLastName(String pdLastName) {
		this.pdLastName = pdLastName;
	}

	public String getPdFirstName() {
		return this.pdFirstName;
	}

	public void setPdFirstName(String pdFirstName) {
		this.pdFirstName = pdFirstName;
	}

	public String getPdMiName() {
		return this.pdMiName;
	}

	public void setPdMiName(String pdMiName) {
		this.pdMiName = pdMiName;
	}

	public String getPdUserId() {
		return this.pdUserId;
	}

	public void setPdUserId(String pdUserId) {
		this.pdUserId = pdUserId;
	}

	public String getGmsCode() {
		return this.gmsCode;
	}

	public void setGmsCode(String gmsCode) {
		this.gmsCode = gmsCode;
	}

	public Integer getGmsNpeId() {
		return this.gmsNpeId;
	}

	public void setGmsNpeId(Integer gmsNpeId) {
		this.gmsNpeId = gmsNpeId;
	}

	public Integer getGmsNpnId() {
		return this.gmsNpnId;
	}

	public void setGmsNpnId(Integer gmsNpnId) {
		this.gmsNpnId = gmsNpnId;
	}

	public String getGmsLastName() {
		return this.gmsLastName;
	}

	public void setGmsLastName(String gmsLastName) {
		this.gmsLastName = gmsLastName;
	}

	public String getGmsFirstName() {
		return this.gmsFirstName;
	}

	public void setGmsFirstName(String gmsFirstName) {
		this.gmsFirstName = gmsFirstName;
	}

	public String getGmsMiName() {
		return this.gmsMiName;
	}

	public void setGmsMiName(String gmsMiName) {
		this.gmsMiName = gmsMiName;
	}

	public String getGmsUserId() {
		return this.gmsUserId;
	}

	public void setGmsUserId(String gmsUserId) {
		this.gmsUserId = gmsUserId;
	}

	public String getBkupGmsCode() {
		return this.bkupGmsCode;
	}

	public void setBkupGmsCode(String bkupGmsCode) {
		this.bkupGmsCode = bkupGmsCode;
	}

	public Integer getBkupGmsNpeId() {
		return this.bkupGmsNpeId;
	}

	public void setBkupGmsNpeId(Integer bkupGmsNpeId) {
		this.bkupGmsNpeId = bkupGmsNpeId;
	}

	public Integer getBkupGmsNpnId() {
		return this.bkupGmsNpnId;
	}

	public void setBkupGmsNpnId(Integer bkupGmsNpnId) {
		this.bkupGmsNpnId = bkupGmsNpnId;
	}

	public String getBkupGmsLastName() {
		return this.bkupGmsLastName;
	}

	public void setBkupGmsLastName(String bkupGmsLastName) {
		this.bkupGmsLastName = bkupGmsLastName;
	}

	public String getBkupGmsFirstName() {
		return this.bkupGmsFirstName;
	}

	public void setBkupGmsFirstName(String bkupGmsFirstName) {
		this.bkupGmsFirstName = bkupGmsFirstName;
	}

	public String getBkupGmsMiName() {
		return this.bkupGmsMiName;
	}

	public void setBkupGmsMiName(String bkupGmsMiName) {
		this.bkupGmsMiName = bkupGmsMiName;
	}

	public String getBkupGmsUserId() {
		return this.bkupGmsUserId;
	}

	public void setBkupGmsUserId(String bkupGmsUserId) {
		this.bkupGmsUserId = bkupGmsUserId;
	}

	public String getAllGmsUserids() {
		return this.allGmsUserids;
	}

	public void setAllGmsUserids(String allGmsUserids) {
		this.allGmsUserids = allGmsUserids;
	}

	public String getPgmFormStatus() {
		return this.pgmFormStatus;
	}

	public void setPgmFormStatus(String pgmFormStatus) {
		this.pgmFormStatus = pgmFormStatus;
	}

	public Date getPgmFormSubmittedDate() {
		return this.pgmFormSubmittedDate;
	}

	public void setPgmFormSubmittedDate(Date pgmFormSubmittedDate) {
		this.pgmFormSubmittedDate = pgmFormSubmittedDate;
	}

	public String getSpecFormStatus() {
		return this.specFormStatus;
	}

	public void setSpecFormStatus(String specFormStatus) {
		this.specFormStatus = specFormStatus;
	}

	public Date getSpecFormSubmittedDate() {
		return this.specFormSubmittedDate;
	}

	public void setSpecFormSubmittedDate(Date specFormSubmittedDate) {
		this.specFormSubmittedDate = specFormSubmittedDate;
	}

	public String getDmFormStatus() {
		return this.dmFormStatus;
	}

	public void setDmFormStatus(String dmFormStatus) {
		this.dmFormStatus = dmFormStatus;
	}

	public Boolean getMbMinorityFlag() {
		return this.mbMinorityFlag;
	}

	public void setMbMinorityFlag(Boolean mbMinorityFlag) {
		this.mbMinorityFlag = mbMinorityFlag;
	}

	public String getPgmGsReadyFlag() {
		return this.pgmGsReadyFlag;
	}

	public void setPgmGsReadyFlag(String pgmGsReadyFlag) {
		this.pgmGsReadyFlag = pgmGsReadyFlag;
	}

	public String getGpmatsDayCountNum() {
		return this.gpmatsDayCountNum;
	}

	public void setGpmatsDayCountNum(String gpmatsDayCountNum) {
		this.gpmatsDayCountNum = gpmatsDayCountNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormGrantId))
			return false;
		FormGrantId castOther = (FormGrantId) other;

		return ((this.getDummyFlag() == castOther.getDummyFlag()) || (this.getDummyFlag() != null
				&& castOther.getDummyFlag() != null && this.getDummyFlag().equals(castOther.getDummyFlag())))
				&& ((this.getOnControlFlag() == castOther.getOnControlFlag())
						|| (this.getOnControlFlag() != null && castOther.getOnControlFlag() != null
								&& this.getOnControlFlag().equals(castOther.getOnControlFlag())))
				&& ((this.getElectronicSubmissionFlag() == castOther.getElectronicSubmissionFlag())
						|| (this.getElectronicSubmissionFlag() != null
								&& castOther.getElectronicSubmissionFlag() != null
								&& this.getElectronicSubmissionFlag().equals(castOther.getElectronicSubmissionFlag())))
				&& ((this.getApplId() == castOther.getApplId()) || (this.getApplId() != null
						&& castOther.getApplId() != null && this.getApplId().equals(castOther.getApplId())))
				&& ((this.getFullGrantNum() == castOther.getFullGrantNum())
						|| (this.getFullGrantNum() != null && castOther.getFullGrantNum() != null
								&& this.getFullGrantNum().equals(castOther.getFullGrantNum())))
				&& ((this.getRfaPaNumber() == castOther.getRfaPaNumber())
						|| (this.getRfaPaNumber() != null && castOther.getRfaPaNumber() != null
								&& this.getRfaPaNumber().equals(castOther.getRfaPaNumber())))
				&& ((this.getCouncilMeetingDate() == castOther.getCouncilMeetingDate())
						|| (this.getCouncilMeetingDate() != null && castOther.getCouncilMeetingDate() != null
								&& this.getCouncilMeetingDate().equals(castOther.getCouncilMeetingDate())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getMiName() == castOther.getMiName()) || (this.getMiName() != null
						&& castOther.getMiName() != null && this.getMiName().equals(castOther.getMiName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getPiName() == castOther.getPiName()) || (this.getPiName() != null
						&& castOther.getPiName() != null && this.getPiName().equals(castOther.getPiName())))
				&& ((this.getIrgPercentileNum() == castOther.getIrgPercentileNum())
						|| (this.getIrgPercentileNum() != null && castOther.getIrgPercentileNum() != null
								&& this.getIrgPercentileNum().equals(castOther.getIrgPercentileNum())))
				&& ((this.getPriorityScoreNum() == castOther.getPriorityScoreNum())
						|| (this.getPriorityScoreNum() != null && castOther.getPriorityScoreNum() != null
								&& this.getPriorityScoreNum().equals(castOther.getPriorityScoreNum())))
				&& ((this.getApplTypeCode() == castOther.getApplTypeCode())
						|| (this.getApplTypeCode() != null && castOther.getApplTypeCode() != null
								&& this.getApplTypeCode().equals(castOther.getApplTypeCode())))
				&& ((this.getAdminPhsOrgCode() == castOther.getAdminPhsOrgCode())
						|| (this.getAdminPhsOrgCode() != null && castOther.getAdminPhsOrgCode() != null
								&& this.getAdminPhsOrgCode().equals(castOther.getAdminPhsOrgCode())))
				&& ((this.getActivityCode() == castOther.getActivityCode())
						|| (this.getActivityCode() != null && castOther.getActivityCode() != null
								&& this.getActivityCode().equals(castOther.getActivityCode())))
				&& ((this.getSerialNum() == castOther.getSerialNum()) || (this.getSerialNum() != null
						&& castOther.getSerialNum() != null && this.getSerialNum().equals(castOther.getSerialNum())))
				&& ((this.getSupportYear() == castOther.getSupportYear())
						|| (this.getSupportYear() != null && castOther.getSupportYear() != null
								&& this.getSupportYear().equals(castOther.getSupportYear())))
				&& ((this.getSuffixCode() == castOther.getSuffixCode()) || (this.getSuffixCode() != null
						&& castOther.getSuffixCode() != null && this.getSuffixCode().equals(castOther.getSuffixCode())))
				&& ((this.getApplStatusCode() == castOther.getApplStatusCode())
						|| (this.getApplStatusCode() != null && castOther.getApplStatusCode() != null
								&& this.getApplStatusCode().equals(castOther.getApplStatusCode())))
				&& ((this.getApplStatusGroupCode() == castOther.getApplStatusGroupCode())
						|| (this.getApplStatusGroupCode() != null && castOther.getApplStatusGroupCode() != null
								&& this.getApplStatusGroupCode().equals(castOther.getApplStatusGroupCode())))
				&& ((this.getFormerNum() == castOther.getFormerNum()) || (this.getFormerNum() != null
						&& castOther.getFormerNum() != null && this.getFormerNum().equals(castOther.getFormerNum())))
				&& ((this.getBudgetStartDate() == castOther.getBudgetStartDate())
						|| (this.getBudgetStartDate() != null && castOther.getBudgetStartDate() != null
								&& this.getBudgetStartDate().equals(castOther.getBudgetStartDate())))
				&& ((this.getLatestBudgetStartDate() == castOther.getLatestBudgetStartDate())
						|| (this.getLatestBudgetStartDate() != null && castOther.getLatestBudgetStartDate() != null
								&& this.getLatestBudgetStartDate().equals(castOther.getLatestBudgetStartDate())))
				&& ((this.getFy() == castOther.getFy()) || (this.getFy() != null && castOther.getFy() != null
						&& this.getFy().equals(castOther.getFy())))
				&& ((this.getIpf() == castOther.getIpf()) || (this.getIpf() != null && castOther.getIpf() != null
						&& this.getIpf().equals(castOther.getIpf())))
				&& ((this.getOrgName() == castOther.getOrgName()) || (this.getOrgName() != null
						&& castOther.getOrgName() != null && this.getOrgName().equals(castOther.getOrgName())))
				&& ((this.getWithinPaylineFlag() == castOther.getWithinPaylineFlag())
						|| (this.getWithinPaylineFlag() != null && castOther.getWithinPaylineFlag() != null
								&& this.getWithinPaylineFlag().equals(castOther.getWithinPaylineFlag())))
				&& ((this.getCayCode() == castOther.getCayCode()) || (this.getCayCode() != null
						&& castOther.getCayCode() != null && this.getCayCode().equals(castOther.getCayCode())))
				&& ((this.getRoleUsageCode() == castOther.getRoleUsageCode())
						|| (this.getRoleUsageCode() != null && castOther.getRoleUsageCode() != null
								&& this.getRoleUsageCode().equals(castOther.getRoleUsageCode())))
				&& ((this.getPdNpeId() == castOther.getPdNpeId()) || (this.getPdNpeId() != null
						&& castOther.getPdNpeId() != null && this.getPdNpeId().equals(castOther.getPdNpeId())))
				&& ((this.getPdNpnId() == castOther.getPdNpnId()) || (this.getPdNpnId() != null
						&& castOther.getPdNpnId() != null && this.getPdNpnId().equals(castOther.getPdNpnId())))
				&& ((this.getPdLastName() == castOther.getPdLastName()) || (this.getPdLastName() != null
						&& castOther.getPdLastName() != null && this.getPdLastName().equals(castOther.getPdLastName())))
				&& ((this.getPdFirstName() == castOther.getPdFirstName())
						|| (this.getPdFirstName() != null && castOther.getPdFirstName() != null
								&& this.getPdFirstName().equals(castOther.getPdFirstName())))
				&& ((this.getPdMiName() == castOther.getPdMiName()) || (this.getPdMiName() != null
						&& castOther.getPdMiName() != null && this.getPdMiName().equals(castOther.getPdMiName())))
				&& ((this.getPdUserId() == castOther.getPdUserId()) || (this.getPdUserId() != null
						&& castOther.getPdUserId() != null && this.getPdUserId().equals(castOther.getPdUserId())))
				&& ((this.getGmsCode() == castOther.getGmsCode()) || (this.getGmsCode() != null
						&& castOther.getGmsCode() != null && this.getGmsCode().equals(castOther.getGmsCode())))
				&& ((this.getGmsNpeId() == castOther.getGmsNpeId()) || (this.getGmsNpeId() != null
						&& castOther.getGmsNpeId() != null && this.getGmsNpeId().equals(castOther.getGmsNpeId())))
				&& ((this.getGmsNpnId() == castOther.getGmsNpnId()) || (this.getGmsNpnId() != null
						&& castOther.getGmsNpnId() != null && this.getGmsNpnId().equals(castOther.getGmsNpnId())))
				&& ((this.getGmsLastName() == castOther.getGmsLastName())
						|| (this.getGmsLastName() != null && castOther.getGmsLastName() != null
								&& this.getGmsLastName().equals(castOther.getGmsLastName())))
				&& ((this.getGmsFirstName() == castOther.getGmsFirstName())
						|| (this.getGmsFirstName() != null && castOther.getGmsFirstName() != null
								&& this.getGmsFirstName().equals(castOther.getGmsFirstName())))
				&& ((this.getGmsMiName() == castOther.getGmsMiName()) || (this.getGmsMiName() != null
						&& castOther.getGmsMiName() != null && this.getGmsMiName().equals(castOther.getGmsMiName())))
				&& ((this.getGmsUserId() == castOther.getGmsUserId()) || (this.getGmsUserId() != null
						&& castOther.getGmsUserId() != null && this.getGmsUserId().equals(castOther.getGmsUserId())))
				&& ((this.getBkupGmsCode() == castOther.getBkupGmsCode())
						|| (this.getBkupGmsCode() != null && castOther.getBkupGmsCode() != null
								&& this.getBkupGmsCode().equals(castOther.getBkupGmsCode())))
				&& ((this.getBkupGmsNpeId() == castOther.getBkupGmsNpeId())
						|| (this.getBkupGmsNpeId() != null && castOther.getBkupGmsNpeId() != null
								&& this.getBkupGmsNpeId().equals(castOther.getBkupGmsNpeId())))
				&& ((this.getBkupGmsNpnId() == castOther.getBkupGmsNpnId())
						|| (this.getBkupGmsNpnId() != null && castOther.getBkupGmsNpnId() != null
								&& this.getBkupGmsNpnId().equals(castOther.getBkupGmsNpnId())))
				&& ((this.getBkupGmsLastName() == castOther.getBkupGmsLastName())
						|| (this.getBkupGmsLastName() != null && castOther.getBkupGmsLastName() != null
								&& this.getBkupGmsLastName().equals(castOther.getBkupGmsLastName())))
				&& ((this.getBkupGmsFirstName() == castOther.getBkupGmsFirstName())
						|| (this.getBkupGmsFirstName() != null && castOther.getBkupGmsFirstName() != null
								&& this.getBkupGmsFirstName().equals(castOther.getBkupGmsFirstName())))
				&& ((this.getBkupGmsMiName() == castOther.getBkupGmsMiName())
						|| (this.getBkupGmsMiName() != null && castOther.getBkupGmsMiName() != null
								&& this.getBkupGmsMiName().equals(castOther.getBkupGmsMiName())))
				&& ((this.getBkupGmsUserId() == castOther.getBkupGmsUserId())
						|| (this.getBkupGmsUserId() != null && castOther.getBkupGmsUserId() != null
								&& this.getBkupGmsUserId().equals(castOther.getBkupGmsUserId())))
				&& ((this.getAllGmsUserids() == castOther.getAllGmsUserids())
						|| (this.getAllGmsUserids() != null && castOther.getAllGmsUserids() != null
								&& this.getAllGmsUserids().equals(castOther.getAllGmsUserids())))
				&& ((this.getPgmFormStatus() == castOther.getPgmFormStatus())
						|| (this.getPgmFormStatus() != null && castOther.getPgmFormStatus() != null
								&& this.getPgmFormStatus().equals(castOther.getPgmFormStatus())))
				&& ((this.getPgmFormSubmittedDate() == castOther.getPgmFormSubmittedDate())
						|| (this.getPgmFormSubmittedDate() != null && castOther.getPgmFormSubmittedDate() != null
								&& this.getPgmFormSubmittedDate().equals(castOther.getPgmFormSubmittedDate())))
				&& ((this.getSpecFormStatus() == castOther.getSpecFormStatus())
						|| (this.getSpecFormStatus() != null && castOther.getSpecFormStatus() != null
								&& this.getSpecFormStatus().equals(castOther.getSpecFormStatus())))
				&& ((this.getSpecFormSubmittedDate() == castOther.getSpecFormSubmittedDate())
						|| (this.getSpecFormSubmittedDate() != null && castOther.getSpecFormSubmittedDate() != null
								&& this.getSpecFormSubmittedDate().equals(castOther.getSpecFormSubmittedDate())))
				&& ((this.getDmFormStatus() == castOther.getDmFormStatus())
						|| (this.getDmFormStatus() != null && castOther.getDmFormStatus() != null
								&& this.getDmFormStatus().equals(castOther.getDmFormStatus())))
				&& ((this.getMbMinorityFlag() == castOther.getMbMinorityFlag())
						|| (this.getMbMinorityFlag() != null && castOther.getMbMinorityFlag() != null
								&& this.getMbMinorityFlag().equals(castOther.getMbMinorityFlag())))
				&& ((this.getPgmGsReadyFlag() == castOther.getPgmGsReadyFlag())
						|| (this.getPgmGsReadyFlag() != null && castOther.getPgmGsReadyFlag() != null
								&& this.getPgmGsReadyFlag().equals(castOther.getPgmGsReadyFlag())))
				&& ((this.getGpmatsDayCountNum() == castOther.getGpmatsDayCountNum())
						|| (this.getGpmatsDayCountNum() != null && castOther.getGpmatsDayCountNum() != null
								&& this.getGpmatsDayCountNum().equals(castOther.getGpmatsDayCountNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDummyFlag() == null ? 0 : this.getDummyFlag().hashCode());
		result = 37 * result + (getOnControlFlag() == null ? 0 : this.getOnControlFlag().hashCode());
		result = 37 * result
				+ (getElectronicSubmissionFlag() == null ? 0 : this.getElectronicSubmissionFlag().hashCode());
		result = 37 * result + (getApplId() == null ? 0 : this.getApplId().hashCode());
		result = 37 * result + (getFullGrantNum() == null ? 0 : this.getFullGrantNum().hashCode());
		result = 37 * result + (getRfaPaNumber() == null ? 0 : this.getRfaPaNumber().hashCode());
		result = 37 * result + (getCouncilMeetingDate() == null ? 0 : this.getCouncilMeetingDate().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getMiName() == null ? 0 : this.getMiName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getPiName() == null ? 0 : this.getPiName().hashCode());
		result = 37 * result + (getIrgPercentileNum() == null ? 0 : this.getIrgPercentileNum().hashCode());
		result = 37 * result + (getPriorityScoreNum() == null ? 0 : this.getPriorityScoreNum().hashCode());
		result = 37 * result + (getApplTypeCode() == null ? 0 : this.getApplTypeCode().hashCode());
		result = 37 * result + (getAdminPhsOrgCode() == null ? 0 : this.getAdminPhsOrgCode().hashCode());
		result = 37 * result + (getActivityCode() == null ? 0 : this.getActivityCode().hashCode());
		result = 37 * result + (getSerialNum() == null ? 0 : this.getSerialNum().hashCode());
		result = 37 * result + (getSupportYear() == null ? 0 : this.getSupportYear().hashCode());
		result = 37 * result + (getSuffixCode() == null ? 0 : this.getSuffixCode().hashCode());
		result = 37 * result + (getApplStatusCode() == null ? 0 : this.getApplStatusCode().hashCode());
		result = 37 * result + (getApplStatusGroupCode() == null ? 0 : this.getApplStatusGroupCode().hashCode());
		result = 37 * result + (getFormerNum() == null ? 0 : this.getFormerNum().hashCode());
		result = 37 * result + (getBudgetStartDate() == null ? 0 : this.getBudgetStartDate().hashCode());
		result = 37 * result + (getLatestBudgetStartDate() == null ? 0 : this.getLatestBudgetStartDate().hashCode());
		result = 37 * result + (getFy() == null ? 0 : this.getFy().hashCode());
		result = 37 * result + (getIpf() == null ? 0 : this.getIpf().hashCode());
		result = 37 * result + (getOrgName() == null ? 0 : this.getOrgName().hashCode());
		result = 37 * result + (getWithinPaylineFlag() == null ? 0 : this.getWithinPaylineFlag().hashCode());
		result = 37 * result + (getCayCode() == null ? 0 : this.getCayCode().hashCode());
		result = 37 * result + (getRoleUsageCode() == null ? 0 : this.getRoleUsageCode().hashCode());
		result = 37 * result + (getPdNpeId() == null ? 0 : this.getPdNpeId().hashCode());
		result = 37 * result + (getPdNpnId() == null ? 0 : this.getPdNpnId().hashCode());
		result = 37 * result + (getPdLastName() == null ? 0 : this.getPdLastName().hashCode());
		result = 37 * result + (getPdFirstName() == null ? 0 : this.getPdFirstName().hashCode());
		result = 37 * result + (getPdMiName() == null ? 0 : this.getPdMiName().hashCode());
		result = 37 * result + (getPdUserId() == null ? 0 : this.getPdUserId().hashCode());
		result = 37 * result + (getGmsCode() == null ? 0 : this.getGmsCode().hashCode());
		result = 37 * result + (getGmsNpeId() == null ? 0 : this.getGmsNpeId().hashCode());
		result = 37 * result + (getGmsNpnId() == null ? 0 : this.getGmsNpnId().hashCode());
		result = 37 * result + (getGmsLastName() == null ? 0 : this.getGmsLastName().hashCode());
		result = 37 * result + (getGmsFirstName() == null ? 0 : this.getGmsFirstName().hashCode());
		result = 37 * result + (getGmsMiName() == null ? 0 : this.getGmsMiName().hashCode());
		result = 37 * result + (getGmsUserId() == null ? 0 : this.getGmsUserId().hashCode());
		result = 37 * result + (getBkupGmsCode() == null ? 0 : this.getBkupGmsCode().hashCode());
		result = 37 * result + (getBkupGmsNpeId() == null ? 0 : this.getBkupGmsNpeId().hashCode());
		result = 37 * result + (getBkupGmsNpnId() == null ? 0 : this.getBkupGmsNpnId().hashCode());
		result = 37 * result + (getBkupGmsLastName() == null ? 0 : this.getBkupGmsLastName().hashCode());
		result = 37 * result + (getBkupGmsFirstName() == null ? 0 : this.getBkupGmsFirstName().hashCode());
		result = 37 * result + (getBkupGmsMiName() == null ? 0 : this.getBkupGmsMiName().hashCode());
		result = 37 * result + (getBkupGmsUserId() == null ? 0 : this.getBkupGmsUserId().hashCode());
		result = 37 * result + (getAllGmsUserids() == null ? 0 : this.getAllGmsUserids().hashCode());
		result = 37 * result + (getPgmFormStatus() == null ? 0 : this.getPgmFormStatus().hashCode());
		result = 37 * result + (getPgmFormSubmittedDate() == null ? 0 : this.getPgmFormSubmittedDate().hashCode());
		result = 37 * result + (getSpecFormStatus() == null ? 0 : this.getSpecFormStatus().hashCode());
		result = 37 * result + (getSpecFormSubmittedDate() == null ? 0 : this.getSpecFormSubmittedDate().hashCode());
		result = 37 * result + (getDmFormStatus() == null ? 0 : this.getDmFormStatus().hashCode());
		result = 37 * result + (getMbMinorityFlag() == null ? 0 : this.getMbMinorityFlag().hashCode());
		result = 37 * result + (getPgmGsReadyFlag() == null ? 0 : this.getPgmGsReadyFlag().hashCode());
		result = 37 * result + (getGpmatsDayCountNum() == null ? 0 : this.getGpmatsDayCountNum().hashCode());
		return result;
	}

}
