package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * FormTemplatesDraft generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormTemplatesDraft implements java.io.Serializable {

	private Integer id;
	private FormModulesDraft formModulesDraft;
	private String templateHtml;
	private Integer revisionNum;
	private Integer updateStamp;
	private String templateXml;
	private String description;
	private Date gsfbChangeDate;
	private String gsfbChangedUserId;
	private String gsfbCreatedUserId;
	private String name;
	private String templateUuid;
	private List<FormElementsDraft> formElementsDrafts = new ArrayList<FormElementsDraft>();
	// No need for hashCode() and equal() methods. This is inside a session and Hibernate guarantees equivalence of persistent identity (database row) and Java identity inside a particular session scope.
	private Set<FormTemplatesMatrixDraft> formTemplatesMatrixDrafts = new HashSet<FormTemplatesMatrixDraft>(0);
	private Set<FormGrantMatrixDraft> formGrantMatrixDrafts = new HashSet<FormGrantMatrixDraft>(0);


	public FormTemplatesDraft() {
	}

	public FormTemplatesDraft(Integer id, String templateHtml, Integer revisionNum) {
		this.id = id;
		this.templateHtml = templateHtml;
		this.revisionNum = revisionNum;
	}

	public FormTemplatesDraft(Integer id, FormModulesDraft formModulesDraft, String templateHtml, Integer revisionNum,
			Integer updateStamp, String templateXml, String description, Date gsfbChangeDate, String gsfbChangedUserId,
			String gsfbCreatedUserId, String name, String templateUuid, List<FormElementsDraft> formElementsDrafts,
			Set<FormTemplatesMatrixDraft> formTemplatesMatrixDrafts, Set<FormGrantMatrixDraft> formGrantMatrixDrafts) {
		this.id = id;
		this.formModulesDraft = formModulesDraft;
		this.templateHtml = templateHtml;
		this.revisionNum = revisionNum;
		this.updateStamp = updateStamp;
		this.templateXml = templateXml;
		this.description = description;
		this.gsfbChangeDate = gsfbChangeDate;
		this.gsfbChangedUserId = gsfbChangedUserId;
		this.gsfbCreatedUserId = gsfbCreatedUserId;
		this.name = name;
		this.templateUuid = templateUuid;
		this.formElementsDrafts = formElementsDrafts;
		this.formTemplatesMatrixDrafts = formTemplatesMatrixDrafts;
		this.formGrantMatrixDrafts = formGrantMatrixDrafts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormModulesDraft getFormModulesDraft() {
		return this.formModulesDraft;
	}

	public void setFormModulesDraft(FormModulesDraft formModulesDraft) {
		this.formModulesDraft = formModulesDraft;
	}

	public String getTemplateHtml() {
		return this.templateHtml;
	}

	public void setTemplateHtml(String templateHtml) {
		this.templateHtml = templateHtml;
	}

	public Integer getRevisionNum() {
		return this.revisionNum;
	}

	public void setRevisionNum(Integer revisionNum) {
		this.revisionNum = revisionNum;
	}

	public Integer getUpdateStamp() {
		return this.updateStamp;
	}

	public void setUpdateStamp(Integer updateStamp) {
		this.updateStamp = updateStamp;
	}

	public String getTemplateXml() {
		return this.templateXml;
	}

	public void setTemplateXml(String templateXml) {
		this.templateXml = templateXml;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getGsfbChangeDate() {
		return this.gsfbChangeDate;
	}

	public void setGsfbChangeDate(Date gsfbChangeDate) {
		this.gsfbChangeDate = gsfbChangeDate;
	}

	public String getGsfbChangedUserId() {
		return this.gsfbChangedUserId;
	}

	public void setGsfbChangedUserId(String gsfbChangedUserId) {
		this.gsfbChangedUserId = gsfbChangedUserId;
	}

	public String getGsfbCreatedUserId() {
		return this.gsfbCreatedUserId;
	}

	public void setGsfbCreatedUserId(String gsfbCreatedUserId) {
		this.gsfbCreatedUserId = gsfbCreatedUserId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTemplateUuid() {
		return this.templateUuid;
	}

	public void setTemplateUuid(String templateUuid) {
		this.templateUuid = templateUuid;
	}

	public List<FormElementsDraft> getFormElementsDrafts() {
		return this.formElementsDrafts;
	}

	public void setFormElementsDrafts(List<FormElementsDraft> formElementsDrafts) {
		this.formElementsDrafts = formElementsDrafts;
	}

	public Set<FormTemplatesMatrixDraft> getFormTemplatesMatrixDrafts() {
		return this.formTemplatesMatrixDrafts;
	}

	public void setFormTemplatesMatrixDrafts(Set<FormTemplatesMatrixDraft> formTemplatesMatrixDrafts) {
		this.formTemplatesMatrixDrafts = formTemplatesMatrixDrafts;
	}

	public Set<FormGrantMatrixDraft> getFormGrantMatrixDrafts() {
		return this.formGrantMatrixDrafts;
	}

	public void setFormGrantMatrixDrafts(Set<FormGrantMatrixDraft> formGrantMatrixDrafts) {
		this.formGrantMatrixDrafts = formGrantMatrixDrafts;
	}

	public FormTemplates toFormTemplate(){
		FormTemplates ft = new FormTemplates();
		ft.setDescription(this.description);
		ft.setGsfbCreatedUserId(this.gsfbCreatedUserId);
		ft.setGsfbChangedUserId(this.gsfbChangedUserId);
		ft.setGsfbChangeDate(this.gsfbChangeDate);
		ft.setCreateDate(new Date());
		ft.setTemplateUuid(this.templateUuid);
		ft.setName(this.name);
		ft.setTemplateHtml(this.templateHtml);
		ft.setTemplateXml(this.templateXml);
		ft.setRevisionNum(this.revisionNum);
	
		return ft;
	}
}
