package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * FormQuestionAnswersDraft generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormQuestionAnswersDraft implements java.io.Serializable {

	private Integer id;
	private String extrnalQuestionId;
	private String extrnalRespDefId;
	private String extrnalSelcDefId;
	private String stringValue;
	private String textValue;
	private Integer numberValue;
	private Date dateValue;
	private String commentValue;

	public FormQuestionAnswersDraft() {
	}

	public FormQuestionAnswersDraft(Integer id) {
		this.id = id;
	}

	public FormQuestionAnswersDraft(Integer id, String extrnalQuestionId, String extrnalRespDefId,
			String extrnalSelcDefId, String stringValue, String textValue, Integer numberValue, Date dateValue,
			String commentValue) {
		this.id = id;
		this.extrnalQuestionId = extrnalQuestionId;
		this.extrnalRespDefId = extrnalRespDefId;
		this.extrnalSelcDefId = extrnalSelcDefId;
		this.stringValue = stringValue;
		this.textValue = textValue;
		this.numberValue = numberValue;
		this.dateValue = dateValue;
		this.commentValue = commentValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getExtrnalQuestionId() {
		return this.extrnalQuestionId;
	}

	public void setExtrnalQuestionId(String extrnalQuestionId) {
		this.extrnalQuestionId = extrnalQuestionId;
	}

	public String getExtrnalRespDefId() {
		return this.extrnalRespDefId;
	}

	public void setExtrnalRespDefId(String extrnalRespDefId) {
		this.extrnalRespDefId = extrnalRespDefId;
	}

	public String getExtrnalSelcDefId() {
		return this.extrnalSelcDefId;
	}

	public void setExtrnalSelcDefId(String extrnalSelcDefId) {
		this.extrnalSelcDefId = extrnalSelcDefId;
	}

	public String getStringValue() {
		return this.stringValue;
	}

	public void setStringValue(String stringValue) {
		this.stringValue = stringValue;
	}

	public String getTextValue() {
		return this.textValue;
	}

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

	public Integer getNumberValue() {
		return this.numberValue;
	}

	public void setNumberValue(Integer numberValue) {
		this.numberValue = numberValue;
	}

	public Date getDateValue() {
		return this.dateValue;
	}

	public void setDateValue(Date dateValue) {
		this.dateValue = dateValue;
	}

	public String getCommentValue() {
		return this.commentValue;
	}

	public void setCommentValue(String commentValue) {
		this.commentValue = commentValue;
	}
}
