package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormGrant generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormGrant implements java.io.Serializable {

	private FormGrantId id;

	public FormGrant() {
	}

	public FormGrant(FormGrantId id) {
		this.id = id;
	}

	public FormGrantId getId() {
		return this.id;
	}

	public void setId(FormGrantId id) {
		this.id = id;
	}

}
