package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * FormAnswersDraft generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormAnswersDraft implements java.io.Serializable {

	private Integer id;
	private FormQuestionsDraft formQuestionsDraft;
	private String gsAnswerId;
	private String answerUuid;
	private Integer order;
	private String text;
	private String value;
	private Boolean default_;
	// No need for hashCode() and equal() methods. This is inside a session and Hibernate guarantees equivalence of persistent identity (database row) and Java identity inside a particular session scope.
	private Set<FormElementsDraft> formElementsDrafts = new HashSet<FormElementsDraft>(0);

	public FormAnswersDraft() {
	}

	public FormAnswersDraft(Integer id) {
		this.id = id;
	}

	public FormAnswersDraft(Integer id, FormQuestionsDraft formQuestionsDraft, String gsAnswerId, String answerUuid,
			Integer order, String text, String value, Boolean default_, Set<FormElementsDraft> formElementsDrafts) {
		this.id = id;
		this.formQuestionsDraft = formQuestionsDraft;
		this.gsAnswerId = gsAnswerId;
		this.answerUuid = answerUuid;
		this.order = order;
		this.text = text;
		this.value = value;
		this.default_ = default_;
		this.formElementsDrafts = formElementsDrafts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormQuestionsDraft getFormQuestionsDraft() {
		return this.formQuestionsDraft;
	}

	public void setFormQuestionsDraft(FormQuestionsDraft formQuestionsDraft) {
		this.formQuestionsDraft = formQuestionsDraft;
	}

	public String getGsAnswerId() {
		return this.gsAnswerId;
	}

	public void setGsAnswerId(String gsAnswerId) {
		this.gsAnswerId = gsAnswerId;
	}

	public String getAnswerUuid() {
		return this.answerUuid;
	}

	public void setAnswerUuid(String answerUuid) {
		this.answerUuid = answerUuid;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Boolean getDefault_() {
		return this.default_;
	}

	public void setDefault_(Boolean default_) {
		this.default_ = default_;
	}

	public Set<FormElementsDraft> getFormElementsDrafts() {
		return this.formElementsDrafts;
	}

	public void setFormElementsDrafts(Set<FormElementsDraft> formElementsDrafts) {
		this.formElementsDrafts = formElementsDrafts;
	}

}
