package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormGrantMatrix generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormGrantMatrix implements java.io.Serializable {

	private Integer id;
	private FormTemplates formTemplates;
	private String formRoleCode;
	private String applTypeCode;
	private String majorActivityCode;
	private String activityCode;
	private Integer updateStamp;
	private String otherCriteria;

	public FormGrantMatrix() {
	}

	public FormGrantMatrix(Integer id, FormTemplates formTemplates, String formRoleCode, String applTypeCode,
			String majorActivityCode, String activityCode) {
		this.id = id;
		this.formTemplates = formTemplates;
		this.formRoleCode = formRoleCode;
		this.applTypeCode = applTypeCode;
		this.majorActivityCode = majorActivityCode;
		this.activityCode = activityCode;
	}

	public FormGrantMatrix(Integer id, FormTemplates formTemplates, String formRoleCode, String applTypeCode,
			String majorActivityCode, String activityCode, Integer updateStamp, String otherCriteria) {
		this.id = id;
		this.formTemplates = formTemplates;
		this.formRoleCode = formRoleCode;
		this.applTypeCode = applTypeCode;
		this.majorActivityCode = majorActivityCode;
		this.activityCode = activityCode;
		this.updateStamp = updateStamp;
		this.otherCriteria = otherCriteria;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormTemplates getFormTemplates() {
		return this.formTemplates;
	}

	public void setFormTemplates(FormTemplates formTemplates) {
		this.formTemplates = formTemplates;
	}

	public String getFormRoleCode() {
		return this.formRoleCode;
	}

	public void setFormRoleCode(String formRoleCode) {
		this.formRoleCode = formRoleCode;
	}

	public String getApplTypeCode() {
		return this.applTypeCode;
	}

	public void setApplTypeCode(String applTypeCode) {
		this.applTypeCode = applTypeCode;
	}

	public String getMajorActivityCode() {
		return this.majorActivityCode;
	}

	public void setMajorActivityCode(String majorActivityCode) {
		this.majorActivityCode = majorActivityCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public Integer getUpdateStamp() {
		return this.updateStamp;
	}

	public void setUpdateStamp(Integer updateStamp) {
		this.updateStamp = updateStamp;
	}

	public String getOtherCriteria() {
		return this.otherCriteria;
	}

	public void setOtherCriteria(String otherCriteria) {
		this.otherCriteria = otherCriteria;
	}

}
