package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * FormElementsDraft generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormElementsDraft implements java.io.Serializable {

	private Integer id;
	private FormTemplatesDraft formTemplatesDraft;
	private FormAnswersDraft formAnswersDraft;
	private FormElementsDraft formElementsDraft;
	private FormQuestionsDraft formQuestionsDraft;
	private String elementUuid;
	private Integer order;
	private Integer hierarchicalOrder;
	private Boolean required;
	private Boolean readonly;
	private String learnMore;
	private String text;
	private String gsfbChangedUserId;
	private Date gsfbChangeDate;
	private Integer updateStamp;
	// No need for hashCode() and equal() methods. This is inside a session and Hibernate guarantees equivalence of persistent identity (database row) and Java identity inside a particular session scope.
	private Set<FormElementsDraft> formElementsDrafts = new HashSet<FormElementsDraft>(0);

	public FormElementsDraft() {
	}

	public FormElementsDraft(Integer id) {
		this.id = id;
	}

	public FormElementsDraft(Integer id, FormTemplatesDraft formTemplatesDraft, FormAnswersDraft formAnswersDraft,
			FormElementsDraft formElementsDraft, FormQuestionsDraft formQuestionsDraft, String elementUuid,
			Integer order, Integer hierarchicalOrder, Boolean required, Boolean readonly, String learnMore, String text,
			String gsfbChangedUserId, Date gsfbChangeDate, Integer updateStamp, Set<FormElementsDraft> formElementsDrafts) {
		this.id = id;
		this.formTemplatesDraft = formTemplatesDraft;
		this.formAnswersDraft = formAnswersDraft;
		this.formElementsDraft = formElementsDraft;
		this.formQuestionsDraft = formQuestionsDraft;
		this.elementUuid = elementUuid;
		this.order = order;
		this.hierarchicalOrder = hierarchicalOrder;
		this.required = required;
		this.readonly = readonly;
		this.learnMore = learnMore;
		this.text = text;
		this.gsfbChangedUserId = gsfbChangedUserId;
		this.gsfbChangeDate = gsfbChangeDate;
		this.updateStamp = updateStamp;
		this.formElementsDrafts = formElementsDrafts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FormTemplatesDraft getFormTemplatesDraft() {
		return this.formTemplatesDraft;
	}

	public void setFormTemplatesDraft(FormTemplatesDraft formTemplatesDraft) {
		this.formTemplatesDraft = formTemplatesDraft;
	}

	public FormAnswersDraft getFormAnswersDraft() {
		return this.formAnswersDraft;
	}

	public void setFormAnswersDraft(FormAnswersDraft formAnswersDraft) {
		this.formAnswersDraft = formAnswersDraft;
	}

	public FormElementsDraft getFormElementsDraft() {
		return this.formElementsDraft;
	}

	public void setFormElementsDraft(FormElementsDraft formElementsDraft) {
		this.formElementsDraft = formElementsDraft;
	}

	public FormQuestionsDraft getFormQuestionsDraft() {
		return this.formQuestionsDraft;
	}

	public void setFormQuestionsDraft(FormQuestionsDraft formQuestionsDraft) {
		this.formQuestionsDraft = formQuestionsDraft;
	}

	public String getElementUuid() {
		return this.elementUuid;
	}

	public void setElementUuid(String elementUuid) {
		this.elementUuid = elementUuid;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Integer getHierarchicalOrder() {
		return this.hierarchicalOrder;
	}

	public void setHierarchicalOrder(Integer hierarchicalOrder) {
		this.hierarchicalOrder = hierarchicalOrder;
	}

	public Boolean getRequired() {
		return this.required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public Boolean getReadonly() {
		return this.readonly;
	}

	public void setReadonly(Boolean readonly) {
		this.readonly = readonly;
	}

	public String getLearnMore() {
		return this.learnMore;
	}

	public void setLearnMore(String learnMore) {
		this.learnMore = learnMore;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getGsfbChangedUserId() {
		return this.gsfbChangedUserId;
	}

	public void setGsfbChangedUserId(String gsfbChangedUserId) {
		this.gsfbChangedUserId = gsfbChangedUserId;
	}

	public Date getGsfbChangeDate() {
		return this.gsfbChangeDate;
	}

	public void setGsfbChangeDate(Date gsfbChangeDate) {
		this.gsfbChangeDate = gsfbChangeDate;
	}

	public Integer getUpdateStamp() {
		return this.updateStamp;
	}

	public void setUpdateStamp(Integer updateStamp) {
		this.updateStamp = updateStamp;
	}

	public Set<FormElementsDraft> getFormElementsDrafts() {
		return this.formElementsDrafts;
	}

	public void setFormElementsDrafts(Set<FormElementsDraft> formElementsDrafts) {
		this.formElementsDrafts = formElementsDrafts;
	}

	public FormElements toFormElements(Map<String, FormQuestions> mapFinalQuestions, Map<String, FormElements> mapElements) {
		FormElements fe = new FormElements();
		fe.setFormQuestions(mapFinalQuestions.get(this.formQuestionsDraft.getGsQuestionId()));
		fe.setElementUuid(this.elementUuid);
		fe.setOrder(this.order);
		fe.setRequired(this.required);
		fe.setReadonly(this.readonly);
		fe.setLearnMore(this.learnMore);
		fe.setText(this.text);
		fe.setGsfbChangedUserId(this.gsfbChangedUserId);
		fe.setGsfbChangeDate(this.gsfbChangeDate);
		fe.setHierarchicalOrder(this.hierarchicalOrder);

		if(this.formElementsDraft != null) {
			String parentAnswerUuid = this.formAnswersDraft.getAnswerUuid();
			FormElements parentElement = mapElements.get(this.formElementsDraft.getElementUuid());
			fe.setFormElements(parentElement);
			if(parentElement.getFormQuestions() != null) {
				for(FormAnswers parentAnswer : parentElement.getFormQuestions().getFormAnswers()) {
					if(parentAnswer.getAnswerUuid().equals(parentAnswerUuid)) {
						fe.setFormAnswers(parentAnswer);
						break;
					}
				}
			}
		}
		
		return fe;
	}
}
