package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormApplStatusId generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormApplStatusId implements java.io.Serializable {

	private Integer applId;
	private String fullGrantNum;
	private Boolean onControlFlag;
	private String pgmFormStatus;
	private String specFormStatus;

	public FormApplStatusId() {
	}

	public FormApplStatusId(Integer applId) {
		this.applId = applId;
	}

	public FormApplStatusId(Integer applId, String fullGrantNum, Boolean onControlFlag, String pgmFormStatus,
			String specFormStatus) {
		this.applId = applId;
		this.fullGrantNum = fullGrantNum;
		this.onControlFlag = onControlFlag;
		this.pgmFormStatus = pgmFormStatus;
		this.specFormStatus = specFormStatus;
	}

	public Integer getApplId() {
		return this.applId;
	}

	public void setApplId(Integer applId) {
		this.applId = applId;
	}

	public String getFullGrantNum() {
		return this.fullGrantNum;
	}

	public void setFullGrantNum(String fullGrantNum) {
		this.fullGrantNum = fullGrantNum;
	}

	public Boolean getOnControlFlag() {
		return this.onControlFlag;
	}

	public void setOnControlFlag(Boolean onControlFlag) {
		this.onControlFlag = onControlFlag;
	}

	public String getPgmFormStatus() {
		return this.pgmFormStatus;
	}

	public void setPgmFormStatus(String pgmFormStatus) {
		this.pgmFormStatus = pgmFormStatus;
	}

	public String getSpecFormStatus() {
		return this.specFormStatus;
	}

	public void setSpecFormStatus(String specFormStatus) {
		this.specFormStatus = specFormStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormApplStatusId))
			return false;
		FormApplStatusId castOther = (FormApplStatusId) other;

		return ((this.getApplId() == castOther.getApplId()) || (this.getApplId() != null
				&& castOther.getApplId() != null && this.getApplId().equals(castOther.getApplId())))
				&& ((this.getFullGrantNum() == castOther.getFullGrantNum())
						|| (this.getFullGrantNum() != null && castOther.getFullGrantNum() != null
								&& this.getFullGrantNum().equals(castOther.getFullGrantNum())))
				&& ((this.getOnControlFlag() == castOther.getOnControlFlag())
						|| (this.getOnControlFlag() != null && castOther.getOnControlFlag() != null
								&& this.getOnControlFlag().equals(castOther.getOnControlFlag())))
				&& ((this.getPgmFormStatus() == castOther.getPgmFormStatus())
						|| (this.getPgmFormStatus() != null && castOther.getPgmFormStatus() != null
								&& this.getPgmFormStatus().equals(castOther.getPgmFormStatus())))
				&& ((this.getSpecFormStatus() == castOther.getSpecFormStatus())
						|| (this.getSpecFormStatus() != null && castOther.getSpecFormStatus() != null
								&& this.getSpecFormStatus().equals(castOther.getSpecFormStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getApplId() == null ? 0 : this.getApplId().hashCode());
		result = 37 * result + (getFullGrantNum() == null ? 0 : this.getFullGrantNum().hashCode());
		result = 37 * result + (getOnControlFlag() == null ? 0 : this.getOnControlFlag().hashCode());
		result = 37 * result + (getPgmFormStatus() == null ? 0 : this.getPgmFormStatus().hashCode());
		result = 37 * result + (getSpecFormStatus() == null ? 0 : this.getSpecFormStatus().hashCode());
		return result;
	}

}
