package gov.nih.nci.cbiit.scimgmt.gs.domain.hibernate;
// Generated Sep 23, 2016 12:13:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * FormApplStatus generated by hbm2java
 */
@SuppressWarnings("serial")
public class FormApplStatus implements java.io.Serializable {

	private FormApplStatusId id;

	public FormApplStatus() {
	}

	public FormApplStatus(FormApplStatusId id) {
		this.id = id;
	}

	public FormApplStatusId getId() {
		return this.id;
	}

	public void setId(FormApplStatusId id) {
		this.id = id;
	}

}
