<!DOCTYPE html SYSTEM "about:legacy-compat"><html lang="en-US"><!-- Engine version 5.10.736.0--><head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Site map for https://i2e-test.nci.nih.gov/gsnew/index.action;jsessionid=9DF7390323BA6CBEEB5FA3B747B52EB0?changeUser=PERKINSU</title><meta name="robots" content="noindex"><meta name="sortsite-ignorerule-page" content="BugHtmlSvg"><meta name="description" content="Site map showing location of issues on https://i2e-test.nci.nih.gov/gsnew/index.action;jsessionid=9DF7390323BA6CBEEB5FA3B747B52EB0?changeUser=PERKINSU"><link rel="shortcut icon" href="http://cdn.pmstatic.com/favicon.ico"><link type="text/css" href="Report/report.min-20120918.css" rel="stylesheet"><style type="text/css">			
				button.chevron
				{
					border: none;
					background: none;
					padding: 0;
					margin: 0;
					vertical-align: middle;
				}
			</style><style type="text/css">
                .accessible
                {
                    position: absolute;
                    left: -10000px;
                    top: auto;
                    width: 1px;
                    height: 1px;
                    overflow: hidden;
                    display:inline;
                }
			</style><!--[if !IE]>--><style type="text/css">
				#guideline { visibility: hidden; }
			</style><!--<![endif]--><!--[if lte IE 8]>
			<style type="text/css">
				tr.disabled td img
				{
					filter: alpha(opacity=30);
				}
				
				div#svgGraph
				{
					display:none;
				}
			</style>
			<![endif]--><!--[if lte IE 7]>
			<style type="text/css">
				div#header 
				{
					height: 38px;
				}

				div.subnav
				{
					/*padding-bottom: 0px;*/
					height: 38px;
				}
			</style>
			<![endif]--><script type="text/javascript" src="Report/jquery.min.js"></script><script type="text/javascript">
						var g_errViewSource = "Viewing the source is only available when the report is viewed in SortSite.";
						var g_viewSourceDir = "";
					</script><script type="text/javascript" src="Report/report.min-20120615.js"></script></head><body onload="pageLoad()" id="sitemap"><h1 class="accessible">Site Report</h1><p class="accessible"><a href="#content">[Skip navigation links]</a></p><noscript><p><strong>Warning:</strong>
				This report will not work correctly when JavaScript is disabled in your browser.
			</p></noscript><form id="form" action="#"><div><input type="hidden" id="expandedRuleList"><div id="header"><ul><li class="selected"><a id="menu-summary" href="map.htm">Summary</a></li><li><a id="menu-issues" href="map.ERR.htm">Issues</a></li><li><a id="menu-all" href="map.INV.htm">Pages</a></li><li id="menu-page-link"><a rel="nofollow" href="https://i2e-test.nci.nih.gov/gsnew/index.action;jsessionid=9DF7390323BA6CBEEB5FA3B747B52EB0?changeUser=PERKINSU">https://i2e-test.nci.nih.gov/gsnew/index.action;jsessionid=9DF7390323BA6CBEEB5FA3B747B52EB0?changeUser=PERKINSU</a></li></ul></div><div id="tab-summary"><div class="subnav"><ul><li id="menu-summary-dashboard"><a href="map.htm">Dashboard</a></li><li id="menu-summary-sitemap" class="selected"><a href="#">Site Map</a></li><li id="menu-summary-rules"><a href="map.RUL.htm">What was Tested</a></li></ul></div><div class="content" id="content"><p class="description">
		This tab shows where errors occur on a map of the site. Each page is represented by a 
		tower, with the widest towers one click from the home page and towers getting narrower
		the more clicks a page is from the home page. The tallest towers indicate pages with most errors.
		Hover over the tops of the towers to see page details. 
	</p><!--POWERMAPPER MAP--></div></div></div></form></body></html>